### ISSUE TITLE
Update undergraduate academic programs

### ISSUE THREAD

**Issue by greenberg-ron** [LoyolaChicagoCS/WebIssues#2]
Please update https://www.luc.edu/cs/academics/undergraduateprograms to read something like the listing below. Each line should continue to link to where it previously linked to except that Math and Computer Science should now link to https://www.luc.edu/math/bsmathcs.shtml , and Physics With Computer Science should link to
https://www.luc.edu/physics/bs_csphysics.shtml .

Also, there are two new ones, Applied Math to link to https://www.luc.edu/math/bsappliedmath.shtml
and Data Science to link to https://www.luc.edu/math/bsmathds.shtml .

Finally, be sure that the "PROGRAMS" sidebar that comes up at the top level of our site gets updated in a consistent fashion; that may require a request to John Drevs or something.

# Undergraduate Programs
## Majors comprised of mostly COMP courses
BS in Communication Networks and Security (legacy) (CNWS-BS)
BS in Computer Science (COMP-BS)
BS in Cybersecurity (CSEC-BS)
BS in Information Technology (ITEC-BS)
BS in Software Engineering (SWEN-BS)
## Interdepartmental majors
BS in Bioinformatics (BIOI-BS administered through Bioinformatics Program)
BS in Mathematics and Computer Science (MCSC-BS administered by Department of Mathematics and Statistics)
BS in Physics and Computer Science (PCSC-BS administered by Department of Physics)
BS in Applied Mathematics (AMTH-BS administered by Department of Mathematics and Statistics)
BS in Data Science (DATA-BS administered by Department of Mathematics and Statistics)
## Minors
Minor in Computer Science (COMP-MINR)
Minor in Computer Crime and Forensics (CCFR-MINR)
Minor in Information Technology (ITEC-MINR)
## Additional information
"Double-Dipping" Rules
BS and MS Dual-Degree Programs

**Comment by lkreismanis** [comment]
DONE
