### ISSUE TITLE
outdated info on CS faculty pages

### ISSUE THREAD

**Issue by klaeufer** [LoyolaChicagoCS/WebIssues#5]
# https://www.luc.edu/cs/people/ftfaculty/

- remove GPD title from Andy
- add "Graduate Program Director (GPD) for Computer Science and Software Engineering" to Konstantin
- add "Graduate Program Director (GPD) for Information Technology" to Channah

# https://www.luc.edu/cs/people/ftfaculty/harringtonandrewn.shtml

- remove GPD title from Andy

# https://www.luc.edu/cs/people/ftfaculty/lauferkonstantin.shtml

- DONE add "Graduate Program Director (GPD) for Computer Science and Software Engineering" to Konstantin

# https://www.luc.edu/cs/people/ftfaculty/naimanchannah.shtml

- add "Graduate Program Director (GPD) for Information Technology" to Channah

**Comment by lkreismanis** [comment]
DONE
