### ISSUE TITLE
Leo should move from PT to FT page

### ISSUE THREAD

**Issue by klaeufer** [LoyolaChicagoCS/WebIssues#8]
**Describe the bug**
Leo should move from PT to FT page

**Which sites are affected**
https://luc.edu/cs - our general web site

**To Reproduce**

https://www.luc.edu/cs/people/ftfaculty/
https://www.luc.edu/cs/people/ptfaculty/

**Expected behavior**
See Leo on FT page

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lkreismanis** [comment]
DONE
