### ISSUE TITLE
PT faculty page should be sorted alphabetically

### ISSUE THREAD

**Issue by klaeufer** [LoyolaChicagoCS/WebIssues#9]
**Describe the bug**
PT faculty page not sorted alphabetically

**Which sites are affected**
https://luc.edu/cs - our general web site

**To Reproduce**

https://www.luc.edu/cs/people/ptfaculty/

**Expected behavior**
sorted alpha

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lkreismanis** [comment]
DONE

**Comment by klaeufer** [comment]
Fixed using the following steps:
1) display 25 (all) rows
2) sort manually
